---
title: "Happy Analysis"
author: "Harika Kovvuri"
date: "2023-02-18"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load New Package
```{r}
#install.packages("shiny")
#install.packages("shinydashboard")
```


#Load Programs
```{r}
library(tidyverse)
library(naniar)
library(janitor)
library(here)
library(shiny)
library(shinydashboard)
library(ggplot2)
```


#Load 2021 Data
```{r}
happy_2021 <-read.csv(here("happiness_data", "2021.csv")) %>% clean_names()
happy_2021
```

#Add 2021 Year Column
```{r}
happy_2021$year <- "2021"
happy_2021
```


#Load 2020 Data
```{r}
happy_2020 <-read.csv(here("happiness_data", "2020.csv")) %>% clean_names()
happy_2020
```

#Add 2020 Year Column
```{r}
happy_2020$year <-"2020"
happy_2020
```

#Retrieve Names
```{r}
names(happy_2020)
```
```{r}
names(happy_2021)
```

#Merge Data Sets
```{r}
merged_happy <-rbind(happy_2021,happy_2020)
```

```{r}
merged_happy
```

#Make New CSV File
```{r}
write.csv(merged_happy,"merged_happy.csv",row.names = F)
```

#Retrieve Newly Merged Data
```{r}
n_happy <- read.csv(here("happiness_data","merged_happy.csv"))
n_happy
```

#Structural Analysis of New Data

```{r}
names(n_happy)
```

```{r}
glimpse(n_happy)
```

#NA Summary
```{r}
naniar::miss_var_summary(n_happy)
```


```{r}
names(n_happy)
```

# Create New Data Frame
```{r}
narrow <- n_happy %>% 
  select(country_name,year,social_support,healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption,logged_gdp_per_capita, dystopia_residual)
narrow
```

#2020 Narrow
```{r}
tw_narrow<-
  narrow%>% 
  filter(year=="2020")
tw_narrow
```

```{r}

names(tw_narrow)
```

#Create Stacked Bar Plot for 2020 Data


```{r}
#make an output the clearly defines x and y
```

```{r}
reorder <- tw_narrow %>% 
  group_by(country_name) %>% 
pivot_longer (-c(country_name,year),
  names_to= "Factors",
  values_to="Score") %>% 
  clean_names()
reorder
```
```{r}
#reorder %>% 
 # group_by(country_name) %>% 
 # ggplot(aes(x=country_name,y=score, fill=factor))+
   # geom_col()
```

